#!/usr/bin/env python
from __future__ import print_function

# -*- coding: utf-8 -*-
import os,re,sys

SPLUNK_SDK_PATH = 'splunk_sdk_python/latest'
splunk_sdk_path = os.getenv('SPLUNK_SDK_PATH', SPLUNK_SDK_PATH)

if not os.path.isdir(splunk_sdk_path):
  raise Exception('Unable to find Splunk SDK Python library: ' + splunk_sdk_path)

sc_dir = os.path.dirname(__file__)
sc_ver = os.environ.get("SPLUNK_CAPTURE_VERSION", os.path.basename(sc_dir))
sc_dir = os.path.dirname(sc_dir)
if not sc_dir:
  sc_dir = "."
sc_dir = "/".join([sc_dir, sc_ver])

sys.path.append(splunk_sdk_path)
sys.path.insert(0, os.path.join(sc_dir))

from splunk_capture import main

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])
    sys.exit(main())
